### ISSUE TITLE
Update gcloud task stages in actions to use the auth workflow.

### ISSUE THREAD

**Issue by aaronrea** [ScaleSec/gcp_org_policy_notifier#111]
See recent failed actions runs for more detail.

**Comment by kaushik853** [comment]
Hi Aaron, Can you share some more detail for this? i can take a look

Thanks
Kaushik

**Comment by aaronrea** [comment]
Hi kaushik853, have a look at recently closed pr #124. There is a (1) deprecation warning for the codql check and an error in the tflint check involving the (2)google cloud auth setup action. 

I think the solution to either of these is to update the respective action to a non deprecated version. Does that make sense?

**Comment by kaushik853** [comment]
> Hi kaushik853, have a look at recently closed pr #124. There is a (1) deprecation warning for the codql check and an error in the tflint check involving the (2)google cloud auth setup action.
> 
> I think the solution to either of these is to update the respective action to a non deprecated version. Does that make sense?

Let me take a look..can also please let me know where do we use codql here?

**Comment by kaushik853** [comment]
Hi Aaron,

I figured where the issue is. i think following change need to be made:
1) in codeql-analysis.yml file change it to v2 from v1. https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
2) in tf.yml file , That 3rd party action is moving away from the convention of using a branch named master.

I can open a PR with the modification, if thats ok.

**Comment by aaronrea** [comment]
Please do. Thanks

**Comment by JackAtScaleSec** [comment]
Addressed via codeql version bump in https://github.com/ScaleSec/gcp_org_policy_notifier/pull/132
