### ISSUE TITLE
Issue in the automated pull request

### ISSUE THREAD

**Issue by jon-trust** [ScaleSec/gcp_org_policy_notifier#267]
Hi there, we have been using your Org Policy Notifier directly from GitHub. I noticed that the automated PRs are not getting merged.

Is it still being maintained? We do love it, and it is helpful for us!

Cheers,
Jon

**Comment by JackAtScaleSec** [comment]
Hello Jon - The PRs failing to be automatically merged were due to an legacy GitHub action used to automate org policy notifications, that had become stale. This has been addressed in https://github.com/ScaleSec/gcp_org_policy_notifier/pull/268, you shouldn't see this issue any longer. 

If you have any other concerns or feedback, please do reach out, thank you.
